apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name:  {{ .Values.kafka.producer.topics.topicTwo.name | quote }}
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  topicName: {{ .Values.kafka.producer.topics.topicTwo.name | quote }}
  partitions: 1
  replicas: 1
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824