global:
  timezone: UTC
  jaeger:
    host: jaeger-collector
    port: 4317

communication-busybox-1:
  image:
    tag: test-30
  kafka:
    broker:
      host: kafka-cluster-kafka-bootstrap
      port: 9093

communication-busybox-2:
  image:
    tag: test-30
  kafka:
    broker:
      host: kafka-cluster-kafka-bootstrap
      port: 9093

communication-busybox-3:
  image:
    tag: test-30
  kafka:
    broker:
      host: kafka-cluster-kafka-bootstrap
      port: 9093

communication-busybox-4:
  image:
    tag: test-30
  kafka:
    broker:
      host: kafka-cluster-kafka-bootstrap
      port: 9093

communication-busybox-5:
  image:
    tag: test-30
  kafka:
    broker:
      host: kafka-cluster-kafka-bootstrap
      port: 9093