global:
  jaeger:
    host: jaeger-agent
    port: 6831

communication-busybox-1:
  image:
    tag: test-20

communication-busybox-2:
  image:
    tag: test-20

communication-busybox-3:
  image:
    tag: test-20

communication-busybox-4:
  image:
    tag: test-20

communication-busybox-5:
  image:
    tag: test-20