apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali
  namespace: istio-system
spec:
  auth:
    strategy: "anonymous"  # no auth on UI
  deployment:
    cluster_wide_access: true
    discovery_selectors:
      default:
        - matchExpressions:
            - key: "namespace"
              operator: In
              values:
                - molnardani
    view_only_mode: false
  server:
    web_root: "/kiali/molnardani"